# Generated by Django 3.1.1 on 2020-10-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20201013_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='portfolio_site',
            new_name='personal_site',
        ),
    ]
